name: Recent Activity

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: activity-workflow/activity-workflow@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: vishal-rankhamb/vishal-rankhamb
          section_marker: "activity"
          output: README.md
